config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'access#login', as: "login"
  get '/signup', to: 'access#signup', as: "signup"
  post '/signup', to: 'access#create', as: "users"
  post '/login', to: 'access#attempt_login', as: "attempt_login"
  delete '/logout', to: 'access#logout', as: 'logout'

  root 'movies#index'
  resources :movies 
  resources :actors 
  resources :access

  post '/movies/add_comment', to: 'comments#create_movie_comment', as: 'create_movie_comment'
  post '/actors/add_comment', to: 'comments#create_actor_comment', as: 'create_actor_comment'
  

  post '/actor_movies/:id', to: 'actor_movies#create', as: 'create_actor'
  post '/movie_actors/:id', to: 'actor_movies#update', as: 'create_movie'
  delete '/movie_actors/:id/delete/:movie_id', to:'actor_movies#destroy', as: 'destroy_movie'
  delete '/actor_movies/:id/delete/:actor_id', to:'actor_movies#delete', as: 'destroy_actor'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  validates :name, presence: true
  has_many :actor_movies
  has_many :movies, through: :actor_movies
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/actor_movie.rb
class ActorMovie < ActiveRecord::Base
  belongs_to :actor
  belongs_to :movie
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true 
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates :title, presence: true
  validates :year, presence: true, numericality: true 
  has_many :actor_movies
  has_many :actors, through: :actor_movies
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, uniqueness: true, presence: true
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def login
    @user = User.new
  end

  def signup
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to movies_path
    else
      render :signup
    end    
  end 

  def attempt_login
    if User.exists?(username: params[:username])
      @user = User.find_by(username: params[:username])
      if @user.authenticate(params[:password])
          session[:user_id] = @user.id
          session[:username] = @user.username
          flash[:notice] = "Welcome #{@user.username}"
          redirect_to movies_path
      else
        flash[:notice] = "Incorrect Password"
        redirect_to login_path
      end    
    else
      flash[:notice] = "Username not found"
      redirect_to login_path
    end  
  end 

  def logout 
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = "You are now logged out."
      redirect_to movies_path
  end 

private
  def user_params
  params.require(:user).permit(:username, :password)
  end
end

app/controllers/actor_movies_controller.rb
class ActorMoviesController < ApplicationController
skip_before_action :verify_authenticity_token
    def create
    movie_id = (Movie.find(params[:id])).id
    movie_id = params[:id]
    @movie = Movie.find(params[:id])
    @actormovie = ActorMovie.new(movie_id: movie_id, actor_id: params[:actor_id])
    @actormovie.save
    redirect_to movie_path(@movie)
    end

    def update
    actor_id = (Actor.find(params[:id])).id
    @actor = Actor.find(params[:id])
    @actormovie = ActorMovie.new(actor_id: actor_id, movie_id: params[:movie_id])
    @actormovie.save
    redirect_to actor_path(@actor)
    end

    def destroy
    @actor = Actor.find(params[:id])
    movie = ActorMovie.find_by(movie_id: params[:movie_id])
    movie.destroy
    redirect_to actor_path(@actor)  
    end

    def delete
    @movie = Movie.find(params[:id])
    actor = ActorMovie.find_by(actor_id: params[:actor_id])
    actor.destroy
    redirect_to movie_path(@movie)  
    end

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def edit
    @actor = Actor.find(params[:id])
  end

  def new
    @actor = Actor.new
  end

  def show
    @actor = Actor.find(params[:id])
    @movies = Movie.all
  end

  def create
    @actor = Actor.new actor_params 
    if @actor.save
      redirect_to actors_path
    else
      render :new  
    end
  end

  def update
    @actor = Actor.find(params[:id])
    @actor.update_attributes actor_params
    if @actor.save
      redirect_to actor_path(@actor)
    else
      render :edit
    end   
  end

  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to actors_path
  end

  private 

    def actor_params
    params.require(:actor).permit(:name)
    end
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create_movie_comment
    @comment = Comment.new comment_params
    @comment.save
    @movie = @comment.commentable
    redirect_to movie_path(@movie)
   
  end

  def create_actor_comment
    @comment = Comment.new comment_params
    @comment.save
    @actor= @comment.commentable
    redirect_to actor_path(@actor) 
  end

  private 
    def comment_params
    params.require(:comment).permit(:commentable_id, :commentable_type, :content)
    end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def show
    @movie = Movie.find(params[:id])
    @actors = Actor.all
  end

  def create
    @movie = Movie.new movie_params 
    if @movie.save
      redirect_to movies_path
    else
      render :new  
    end
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update_attributes(movie_params)
    if @movie.save
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  private 

    def movie_params
    params.require(:movie).permit(:title, :year)
    end  
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/actor_movies_helper.rb
module ActorMoviesHelper
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/access/_form.html.erb
<%= simple_form_for @user, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"} do |f|%>
<div class = row>
  <div class="col-md-4 col-md-offset-4">
    <%= f.input :username, required: true%>
    <%= f.input :password, required: true %>
    <br>
  </div>
</div>
<br>
<div class ="row">
  <div class ="col-md-4 col-md-offset-6">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>
<Br>
  <div class="row">
    <div class = "col-md-4 col-md-offset-5">
      <%=  link_to('Back to Home', movies_path, {class: "btn btn-primary"}) %>
    </div>
  </div>
</div>

app/views/access/login.html.erb
<%= render "shared/navbar" %>
<br><Br>
<div class = "col-md-6 col-md-offset-3">
<%= form_tag(attempt_login_path, method: "post") do %>
  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %>
  <%= label_tag(:password, "Pw:") %>
  <%= password_field_tag(:password) %>  
  <%= submit_tag("Login") %>
<% end %>
</div>

<% flash.each do |key,value| %>
<p>*<%= value %>*</p>
<% end %>

app/views/access/signup.html.erb
<%= render "shared/navbar" %>

<%= simple_form_for @user, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"} do |f|%>
<div class = row>
  <div class="col-md-4 col-md-offset-4">
    <%= f.input :username, required: true%>
    <%= f.input :password, required: true %>
    <br>
  </div>
</div>
<br>
<div class ="row">
  <div class ="col-md-4 col-md-offset-6">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>
<Br>
  <div class="row">
    <div class = "col-md-4 col-md-offset-5">
      <%=  link_to('Back to Home', movies_path, {class: "btn btn-primary"}) %>
    </div>
  </div>
</div>

app/views/actors/_comment.html.erb
<h2 class="text-center">Actor Comments</h2>
 <div class="row">
        <div class ="col-md-10 col-md-offset-1">
          <table class ="table table-striped">
            <tr>
              <th>Actor</th>
              <th>Comment</th>
            </tr>
            <% @actor.comments.each do |comment|  %>
            <tr >
              <td ><%= comment.commentable.name%></td>
              <td ><%=comment.content %></td>
            </tr>
            <% end %>
          </table>     

<h2 class="text-center">Add Comment</h2>
     <%= form_for Comment.new, url: create_actor_comment_path("actor",@actor.id), method: :post do |form| %>
     <p>Comment:</p>
      <%= form.text_area :content, :rows => 5 %>
      <%= form.hidden_field :commentable_type, :value => "Actor" %>
      <%= form.hidden_field :commentable_id, :value => @actor.id %>
    <p><%= submit_tag "Add comment" %></p>
<% end %>

app/views/actors/_form.html.erb
<%= simple_form_for(@actor, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"}) do |f|%>
<div class = row>
  <div class="col-md-2 col-md-offset-5">
    <%= f.input :name%>
    <br>
  </div>
</div>
<br>
<div class ="row">
  <div class ="col-md-3 col-md-offset-5">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>
<Br>
  <div class="row">
    <div class = "col-md-4 col-md-offset-5">
      <%=  link_to('Back to Actors', actors_path, {class: "btn btn-primary"}) %>
    </div>
  </div>
</div>

app/views/actors/edit.html.erb
<%= render "shared/navbar" %>
<br><br>
<div class="container-fluid">

  <h2 class ="text-center">Edit Actors:</h2>
  <br>
  <%= render 'form' %>

app/views/actors/index.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">
  <br><Br>
  <h2 class = "text-center">Actors</h2>
  <br>

  <!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
  <div class="row">
    <div class ="col-md-10 col-md-offset-1">
      <table class ="table table-striped">
        <tr>
          <th>Name</th>
          <th>Info</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        <% @actors.each do |actor| %>
        <tr >
          <td ><%=actor.name %></td>
          <td><%= link_to('Info', actor_path(actor), {class: "btn-xs btn-info"})%></td>
          <td><%= link_to('Edit', edit_actor_path(actor), {class: "btn-xs btn-info"})%></td>
          <td><%= link_to('Delete',actor_path(actor), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-xs btn-danger")%></td>
        </tr>
        <%end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class ="col-md-2 col-md-offset-1">
      <%=  link_to('Add new actor', new_actor_path, {class: "btn btn-primary"}) %>
    </div>
  </div>
</div>

app/views/actors/new.html.erb
<%= render "shared/navbar" %>
<br><br>
<div class="container-fluid">

  <h2 class ="text-center">Add Actors:</h2>
  <br>
  <%= render 'form' %>

app/views/actors/show.html.erb
<%= render "shared/navbar" %>
<Br><Br>
  <div class="container-fluid">

    <h2 class="text-center"><%=@actor.name%> Movies</h2>
    <div class="row">
      <div class ="col-md-10 col-md-offset-1">
        <table class ="table table-striped">
          <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Delete Movie</th>
          </tr>
          <% @actor.movies.each do |movie|  %>
          <tr >
            <td ><%=movie.title %></td>
            <td ><%=movie.year %></td>
            <td><%= link_to('Delete',"/movie_actors/#{params[:id]}/delete/#{movie.id}", method: :delete, data: { confirm: "Are you sure?" }, class: "btn-xs btn-danger")%></td>
          </tr>
          <% end %>
        </table>

        <h1>Add Movie</h1>
        <form action = "/movie_actors/<%=params[:id] %>" method = "post">
          <select class="form-control" name="movie_id">
            <% @movies.each do |movie|  %>
            <% if @actor.movies.exists?(id: movie.id) == false %>
            <option value=<%= movie.id %>><%= movie.title %></option>
            <% end %>
            <% end %>
          </select>
          <button type="submit" class="btn btn-default">Add Movie</button>
        </form>
        <br>
        <div class="row">
          <div class = "col-md-4 col-md-offset-5">
            <%=  link_to('Back to Actors', actors_path, {class: "btn btn-primary"}) %>
          </div>
        </div>
        <%= render 'comment' %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_comment.html.erb
<h2 class="text-center">Movie Comments</h2>
 <div class="row">
        <div class ="col-md-10 col-md-offset-1">
          <table class ="table table-striped">
            <tr>
              <th>Movie</th>
              <th>Comment</th>
            </tr>
            <% @movie.comments.each do |comment|  %>
            <tr >
              <td ><%= comment.commentable.title%></td>
              <td ><%=comment.content %></td>
            </tr>
            <% end %>
          </table>     

<h2 class="text-center">Add Comment</h2>
     <%= form_for Comment.new, url: create_movie_comment_path("movie",@movie.id), method: :post do |form| %>
     <p>Comment:</p>
      <%= form.text_area :content, :rows => 5 %>
      <%= form.hidden_field :commentable_type, :value => "Movie" %>
      <%= form.hidden_field :commentable_id, :value => @movie.id %>
    <p><%= submit_tag "Add comment" %></p>
<% end %>

app/views/movies/_form.html.erb
<%= simple_form_for(@movie, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"}) do |f|%>
<div class = row>
  <div class="col-md-2 col-md-offset-2">
    <%= f.input :title%>
    <br>
  </div>
  <div class = "col-md-1"></div>
  <div class="col-md-2">
    <%= f.input :year%>
    <br>
  </div>
</div>
<br>
<div class ="row">
  <div class = "col-md-2 col-md-offset-2">
    <%=  link_to('Back to Movies', movies_path, {class: "btn btn-primary"}) %>
  </div>
  <div class ="col-md-3 col-md-offset-1">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>
</div>

app/views/movies/edit.html.erb
<%= render "shared/navbar" %>
<br><Br><br>
<div class="container-fluid">

  <h2 class ="text-center">Edit Movie:</h2>
  <br>
<%= render 'form' %>

app/views/movies/index.html.erb
<%= render "shared/navbar" %>
<div class = "col-md-1 col-md-offset-10">
</div>
<h2 class = "text-center"><% flash.each do |key,value| %>
<p><%= value %></p>
<% end %></h2>
<div class="container-fluid">
  <br><Br>
  <h2 class = "text-center">Movies:</h2>
  <br>

  <!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
  <div class="row">
    <div class ="col-md-10 col-md-offset-1">
      <table class ="table table-striped">
        <tr>
          <th>Title</th>
          <th>Year</th>
          <th>Info</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        <% @movies.each do |movie| %>
        <tr >
          <td ><%=movie.title  %></td>
          <td ><%= movie.year %></td>
          <td><%= link_to('Info', movie_path(movie), {class: "btn-xs btn-info"})%></td>
          <td><%= link_to('Edit', edit_movie_path(movie), {class: "btn-xs btn-info"})%></td>
          <td><%= link_to('Delete',movie_path(movie), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-xs btn-danger")%></td>
        </tr>
        <%end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class ="col-md-2 col-md-offset-1">
      <%=  link_to('Add new ', new_movie_path, {class: "btn btn-primary"}) %>
    </div>
    <div class ="col-md-2 col-md-offset-1">
      <%=  link_to('See Actors', actors_path, {class: "btn btn-primary"}) %>
    </div>
  </div>

app/views/movies/new.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">
<Br><Br>
  <h2 class ="text-center">Add Movies:</h2>
  <br>

<%= render 'form' %>

app/views/movies/show.html.erb
<Br><Br>
  <%= render "shared/navbar" %>
  <div class="container-fluid">

    <h2 class = "text-center"> <%= @movie.title%> </h2>

    <!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
    <div class="row">
      <div class ="col-md-6 col-md-offset-3">
        <table class ="table table-striped">
          <tr>
            <th>Movie Title</th>
            <th>Movie Year</th>
          </tr>
          <tr >
            <td ><%=@movie.title  %></td>
            <td ><%= @movie.year %></td>
          </tr>
        </table>
      </div>
    </div>
    <br>
    <h2 class="text-center">Movie Actors</h1>
      <div class="row">
        <div class ="col-md-10 col-md-offset-1">
          <table class ="table table-striped">
            <tr>
              <th>Actor</th>
              <th>Delete</th>
            </tr>
            <% @movie.actors.each do |actor|  %>
            <tr >
              <td ><%=actor.name %></td>
              <td><%= link_to('Delete',"/actor_movies/#{params[:id]}/delete/#{actor.id}", method: :delete, data: { confirm: "Are you sure?" }, class: "btn-xs btn-danger")%></td>
            </tr>
            <% end %>
          </table>

          <h1>Add Actor</h1>
          <form action = "/actor_movies/<%=params[:id] %>" method = "post">
            <select class="form-control" name="actor_id">
              <% @actors.each do |actor|  %>
              <% if @movie.actors.exists?(id: actor.id) == false %>
              <option value=<%= actor.id %>><%= actor.name %></option>
              <%end %>
              <% end %>
            </select>
            <button type="submit" class="btn btn-default">Add Actor</button>
          </form>
<%= render 'comment' %>
    

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/movies">Home</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class = "container-fluid">
  <div class = "col-md-1 col-md-offset-11">
    <% if session[:username] == nil %>
    <p><%= link_to('Login',login_path, class: "btn-lg btn-primary")%></p>
  </div>
  <% else %>
      <p>User: <%= session[:username] %> </p>
    </div>
  <div class="row">
    <div class = "col-md-1 col-md-offset-11">
      <p><%= link_to('Logout',logout_path, method: :delete, data: { confirm: "Really want to leave?" }, class: "btn btn-danger")%></p>
    </div>
  </div>
  <% end %>
</div>